spring.application.name=travel-guide-backend
spring.datasource.url=jdbc:mysql://localhost:3306/travel_db
spring.datasource.username=root
spring.datasource.password=root@0892
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# logback will still be used, but set default logging level
logging.level.root=INFO
logging.level.com.travelguide=DEBUG